# Generated by Django 2.2.1 on 2019-05-20 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('sm_topping_0', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sm_topping_1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sm_topping_2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sm_topping_3', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sm_topping_special', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lg_topping_0', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lg_topping_1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lg_topping_2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lg_topping_3', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lg_topping_special', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='PlatterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('price_sm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_lg', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='SaladType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('sm', 'small'), ('lg', 'large')], default='sm', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('pizza_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.PizzaType')),
                ('toppings', models.ManyToManyField(blank=True, to='orders.PizzaTopping')),
            ],
        ),
    ]
