# Generated by Django 2.2.1 on 2019-05-24 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_subtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubTopping',
        ),
    ]
