# Generated by Django 2.2.1 on 2019-05-25 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_subtopping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubTopping',
        ),
    ]
