# Generated by Django 2.2.1 on 2019-06-08 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_subtopping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('sm', 'small'), ('lg', 'large')], default='sm', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.SubType')),
                ('toppings', models.ManyToManyField(blank=True, to='orders.SubTopping')),
            ],
        ),
    ]
