# Generated by Django 2.2.1 on 2019-06-08 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_sub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='pizza_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='sub_type',
            new_name='type',
        ),
    ]
