# Generated by Django 2.2.1 on 2019-06-10 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='type',
        ),
        migrations.RemoveField(
            model_name='platter',
            name='type',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='type',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='type',
        ),
        migrations.DeleteModel(
            name='Pasta',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Platter',
        ),
        migrations.DeleteModel(
            name='Salad',
        ),
        migrations.DeleteModel(
            name='Sub',
        ),
    ]
