# Generated by Django 2.2.1 on 2019-06-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_pasta_pizza_platter_salad_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
