# Generated by Django 2.2.1 on 2019-06-22 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20190622_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salad',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.PastaType'),
        ),
    ]
